// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using X_HIJA_SYSTEM_RAZORpage.Data;

#nullable disable

namespace X_HIJA_SYSTEM_RAZORpage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("X_HIJA_SYSTEM_RAZORpage.Models.Category", b =>
                {
                    b.Property<int>("CatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatID"));

                    b.Property<string>("CatName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("CatID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CatID = 100,
                            CatName = "UTP",
                            DisplayOrder = 1
                        },
                        new
                        {
                            CatID = 1000,
                            CatName = "Fiber",
                            DisplayOrder = 3
                        },
                        new
                        {
                            CatID = 12,
                            CatName = "UTPXS",
                            DisplayOrder = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
